services:
  - type: web
    name: jitsi-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jitsi_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jitsi_backend.settings
      - key: PYTHON_VERSION
        value: 3.12
